# Generated by Django 4.0.2 on 2022-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_names', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('service_number', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('cemetery', models.CharField(max_length=20)),
                ('aircraft', models.CharField(max_length=20)),
                ('serial_no', models.CharField(max_length=10)),
                ('base', models.CharField(max_length=20)),
                ('circumstance', models.TextField()),
            ],
        ),
    ]
