# Generated by Django 4.0.2 on 2022-03-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airmen',
            name='aircraft',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='base',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='cemetery',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='first_names',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='rank',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='serial_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='service_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='airmen',
            name='unit',
            field=models.CharField(max_length=200),
        ),
    ]
